- name: Log into DockerHub
  community.general.docker_login:
    username: "{{ docker_username }}"
    password: "{{ lookup('env', 'DOCKER_ACCESS_TOKEN') }}"
  register: result
  when: docker_username is defined

# Force pull newer version of an image tag
- name: Pull images
  community.general.docker_image:
    name: "{{ item }}"
    source: pull
    force_source: yes
  loop: "{{ pull_images }}"
  when: pull_images is defined
