- name: Create deploy directory
  file:
    path: "{{ deploy_dir }}"
    state: directory

- name: Copy compose and env files
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_dir }}/{{ item }}"
  loop: "{{ [compose_file, env_files ] | flatten }}"

- name: Deploy stack
  command: docker stack deploy "{{ stack_name }}" -c "{{ compose_file }}"
  args:
    chdir: "{{ deploy_dir }}"
