- name: Create the deploy directory
  file:
    path: "{{ deploy_dir }}"
    state: directory

- name: Copy compose and environment variables files
  include_tasks: copy.yml
  when: "{{ copy_deploy_files }}"

- name: Deploy the stack
  include_tasks: deploy.yml
