- name: Register Docker GPG
  apt_key:
    url: https://download.docker.com/linux/"{{ os }}"/gpg
    state: present

- name: Register Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/"{{ os }}" "{{ distro }}" stable
    state: present

- name: Install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install python docker-compose module
  pip:
    name: docker-compose
